// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: encounter/encounter-service.proto

package encounter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EncounterService_GetApproved_FullMethodName         = "/encounter.EncounterService/GetApproved"
	EncounterService_GetTouristCreated_FullMethodName   = "/encounter.EncounterService/GetTouristCreated"
	EncounterService_GetByUser_FullMethodName           = "/encounter.EncounterService/GetByUser"
	EncounterService_GetApprovedByStatus_FullMethodName = "/encounter.EncounterService/GetApprovedByStatus"
	EncounterService_GetNearby_FullMethodName           = "/encounter.EncounterService/GetNearby"
	EncounterService_GetNearbyByType_FullMethodName     = "/encounter.EncounterService/GetNearbyByType"
	EncounterService_CreateEncounter_FullMethodName     = "/encounter.EncounterService/CreateEncounter"
	EncounterService_UpdateEncounter_FullMethodName     = "/encounter.EncounterService/UpdateEncounter"
	EncounterService_Approve_FullMethodName             = "/encounter.EncounterService/Approve"
	EncounterService_Decline_FullMethodName             = "/encounter.EncounterService/Decline"
	EncounterService_DeleteEncounter_FullMethodName     = "/encounter.EncounterService/DeleteEncounter"
)

// EncounterServiceClient is the client API for EncounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncounterServiceClient interface {
	GetApproved(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	GetTouristCreated(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	GetByUser(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	GetApprovedByStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	GetNearby(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	GetNearbyByType(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error)
	CreateEncounter(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*Encounter, error)
	UpdateEncounter(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*Encounter, error)
	Approve(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*EmptyResponse, error)
	Decline(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteEncounter(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type encounterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncounterServiceClient(cc grpc.ClientConnInterface) EncounterServiceClient {
	return &encounterServiceClient{cc}
}

func (c *encounterServiceClient) GetApproved(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetApproved_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) GetTouristCreated(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetTouristCreated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) GetByUser(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) GetApprovedByStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetApprovedByStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) GetNearby(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetNearby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) GetNearbyByType(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EncountersResponse, error) {
	out := new(EncountersResponse)
	err := c.cc.Invoke(ctx, EncounterService_GetNearbyByType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) CreateEncounter(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*Encounter, error) {
	out := new(Encounter)
	err := c.cc.Invoke(ctx, EncounterService_CreateEncounter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) UpdateEncounter(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*Encounter, error) {
	out := new(Encounter)
	err := c.cc.Invoke(ctx, EncounterService_UpdateEncounter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) Approve(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, EncounterService_Approve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) Decline(ctx context.Context, in *Encounter, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, EncounterService_Decline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encounterServiceClient) DeleteEncounter(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, EncounterService_DeleteEncounter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncounterServiceServer is the server API for EncounterService service.
// All implementations must embed UnimplementedEncounterServiceServer
// for forward compatibility
type EncounterServiceServer interface {
	GetApproved(context.Context, *EmptyRequest) (*EncountersResponse, error)
	GetTouristCreated(context.Context, *EmptyRequest) (*EncountersResponse, error)
	GetByUser(context.Context, *UserIdRequest) (*EncountersResponse, error)
	GetApprovedByStatus(context.Context, *StatusRequest) (*EncountersResponse, error)
	GetNearby(context.Context, *UserIdRequest) (*EncountersResponse, error)
	GetNearbyByType(context.Context, *UserIdRequest) (*EncountersResponse, error)
	CreateEncounter(context.Context, *Encounter) (*Encounter, error)
	UpdateEncounter(context.Context, *Encounter) (*Encounter, error)
	Approve(context.Context, *Encounter) (*EmptyResponse, error)
	Decline(context.Context, *Encounter) (*EmptyResponse, error)
	DeleteEncounter(context.Context, *IdRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedEncounterServiceServer()
}

// UnimplementedEncounterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEncounterServiceServer struct {
}

func (UnimplementedEncounterServiceServer) GetApproved(context.Context, *EmptyRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApproved not implemented")
}
func (UnimplementedEncounterServiceServer) GetTouristCreated(context.Context, *EmptyRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTouristCreated not implemented")
}
func (UnimplementedEncounterServiceServer) GetByUser(context.Context, *UserIdRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUser not implemented")
}
func (UnimplementedEncounterServiceServer) GetApprovedByStatus(context.Context, *StatusRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApprovedByStatus not implemented")
}
func (UnimplementedEncounterServiceServer) GetNearby(context.Context, *UserIdRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearby not implemented")
}
func (UnimplementedEncounterServiceServer) GetNearbyByType(context.Context, *UserIdRequest) (*EncountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyByType not implemented")
}
func (UnimplementedEncounterServiceServer) CreateEncounter(context.Context, *Encounter) (*Encounter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEncounter not implemented")
}
func (UnimplementedEncounterServiceServer) UpdateEncounter(context.Context, *Encounter) (*Encounter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEncounter not implemented")
}
func (UnimplementedEncounterServiceServer) Approve(context.Context, *Encounter) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedEncounterServiceServer) Decline(context.Context, *Encounter) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decline not implemented")
}
func (UnimplementedEncounterServiceServer) DeleteEncounter(context.Context, *IdRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEncounter not implemented")
}
func (UnimplementedEncounterServiceServer) mustEmbedUnimplementedEncounterServiceServer() {}

// UnsafeEncounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncounterServiceServer will
// result in compilation errors.
type UnsafeEncounterServiceServer interface {
	mustEmbedUnimplementedEncounterServiceServer()
}

func RegisterEncounterServiceServer(s grpc.ServiceRegistrar, srv EncounterServiceServer) {
	s.RegisterService(&EncounterService_ServiceDesc, srv)
}

func _EncounterService_GetApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetApproved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetApproved(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_GetTouristCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetTouristCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetTouristCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetTouristCreated(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_GetByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetByUser(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_GetApprovedByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetApprovedByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetApprovedByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetApprovedByStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_GetNearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetNearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetNearby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetNearby(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_GetNearbyByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).GetNearbyByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_GetNearbyByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).GetNearbyByType(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_CreateEncounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Encounter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).CreateEncounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_CreateEncounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).CreateEncounter(ctx, req.(*Encounter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_UpdateEncounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Encounter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).UpdateEncounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_UpdateEncounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).UpdateEncounter(ctx, req.(*Encounter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Encounter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).Approve(ctx, req.(*Encounter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_Decline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Encounter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).Decline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_Decline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).Decline(ctx, req.(*Encounter))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncounterService_DeleteEncounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncounterServiceServer).DeleteEncounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncounterService_DeleteEncounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncounterServiceServer).DeleteEncounter(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncounterService_ServiceDesc is the grpc.ServiceDesc for EncounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encounter.EncounterService",
	HandlerType: (*EncounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApproved",
			Handler:    _EncounterService_GetApproved_Handler,
		},
		{
			MethodName: "GetTouristCreated",
			Handler:    _EncounterService_GetTouristCreated_Handler,
		},
		{
			MethodName: "GetByUser",
			Handler:    _EncounterService_GetByUser_Handler,
		},
		{
			MethodName: "GetApprovedByStatus",
			Handler:    _EncounterService_GetApprovedByStatus_Handler,
		},
		{
			MethodName: "GetNearby",
			Handler:    _EncounterService_GetNearby_Handler,
		},
		{
			MethodName: "GetNearbyByType",
			Handler:    _EncounterService_GetNearbyByType_Handler,
		},
		{
			MethodName: "CreateEncounter",
			Handler:    _EncounterService_CreateEncounter_Handler,
		},
		{
			MethodName: "UpdateEncounter",
			Handler:    _EncounterService_UpdateEncounter_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _EncounterService_Approve_Handler,
		},
		{
			MethodName: "Decline",
			Handler:    _EncounterService_Decline_Handler,
		},
		{
			MethodName: "DeleteEncounter",
			Handler:    _EncounterService_DeleteEncounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encounter/encounter-service.proto",
}
