version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - database
    ports:
      - "5432:5432"
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - type: bind
        source: ./BACK/scripts/tutours-db-backup.sql
        target: /tmp/explorer-init.sql
      - type: bind
        source: ./TOURS_MS/tours.sql
        target: /tmp/tours-init.sql 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_MULTIPLE_DATABASES: tours,explorer
      PGPORT: 5432
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  


  monolit:
    build:
      context: ./BACK
      target: final
    networks:
      - database
    ports:
      - "44333:80"
    restart: on-failure
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
      TOUR_HOST: tour
    depends_on:
      db:
          condition: service_healthy
      tour:
          condition: service_started
      
  tour:
    build: 
      context: ./TOURS_MS
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - database
    environment:
      DB_USER: postgres
      DB_PASSWORD: super
      DB_PORT: 5432
      DB_DATABASE: tours
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

networks:
  database:
    name: database
    driver: bridge

volumes:
  explorer_data:
    driver: local