{
 "title": "MyDashboard",
 "time": { "from": "2024-06-03T12:08:50.843Z", "to": "2024-06-03T12:10:05.628Z" },
 "panels": [
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id!=\"/POD\"}[1m])) by (id) + sum(rate(container_network_transmit_bytes_total{id!=\"/POD\"}[1m])) by (id)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id!=\"/POD\"}[1m])"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id!=\"/POD\"}\n"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{id!=\"/POD\"}\n"
    }
   ]
  }
 ]
}