version: '3.9'

services:
  smart-tutor-migration:
    build:
      dockerfile: Dockerfile
      context: .
      target: execute-migration
    networks:
      - database
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: super
      DATABASE_SCHEMA: explorer

networks:
  database:
    name: database
    driver: bridge
    external: true